name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir gclib/lib gclib/obj obj
    - name: make
      run: make
    - name: make test
      run: make test
